### PR TITLE
Add settings to detect if standard is a project dependency

### PR DESCRIPTION
**Pull request by danreeves**

### CODE REVIEW

**Comment by Flet** [comment]
Is this all thats needed?

**Comment by danreeves** [comment]
afaict. It's not in the docs, but the NodeLinter isn't 🤷‍♀️

src: https://github.com/SublimeLinter/SublimeLinter3/blob/2cab34326b9b8bfe994e1b6d5faa30a6274eb804/lint/node_linter.py#L65-L75

I got it from looking at SublimeLinter-contrib-xo: https://github.com/sindresorhus/SublimeLinter-contrib-xo/pull/6

**Comment by bcomnes** [comment]
Cool wasn't aware of this part of the API

**Comment by danreeves** [comment]
FWIW the CI is failing because PEP rules D203 and D211 conflict; you'll have to disabled one.

e.g. https://github.com/PyCQA/pydocstyle/issues/141

**Comment by Flet** [comment]
Thanks @danreeves! Tagged as 3.1.2 should get picked up soon :)

Also invited as collaborator! 🎉

**Comment by flyingswan3000** [comment]
Standard not lint after upgrade to 3.1.2

Because of `disable_if_not_dependency: true`, linter will be disabled all time, even cannot enable with `Toggle Linter`
It is need to add `disable_if_not_dependency: false` to user setting or project setting to re-enable the linter.
 
due to https://github.com/SublimeLinter/SublimeLinter3/blob/366f602f397f14be84e920f5f0217bce0bce6c01/lint/node_linter.py#L79-L102

only project with `package.json` which dependent `standard` will enable linter.

Shouldn't `disable_if_not_dependency` be `false` by default?

**Comment by cyberwombat** [comment]
I prob missed it when my packages auto updated. Was mostly curious as to true being default. I like that it uses my local if I have one but seems odd imo to have the default to ignore global.

**Comment by danreeves** [comment]
Maybe we should flip the default setting for `disable_if_not_dependency` if this is tripping people up?

**Comment by Flet** [comment]
Yeah flipping the default may be less disruptive. It's your call @danreeves

**Comment by louisl** [comment]
Flip it please. This caught me out today!

**Comment by danreeves** [comment]
I made a new release today flipping the default to False. Sorry for any trouble!

**Pull request merged**
